<?php


namespace App\Hope\Overwrite;


use Dingo\Api\Http\Response\Format\Json;

class JsonFormat extends Json
{
    public function formatEloquentModel($model)
    {
        dd($model);
        return parent::formatEloquentModel($model); // TODO: Change the autogenerated stub
    }

    public function formatArray($content)
    {
        return parent::formatArray($content); // TODO: Change the autogenerated stub
    }
}
